### ISSUE TITLE
License date & name & site

### ISSUE THREAD

**Issue by tomap** [Galad/tranquire#1]
Hi,

Here:
https://github.com/Galad/tranquire/blob/master/LICENSE.txt#L3
You should change: Copyright (c) 2017 Galad https://github.com/Galad/tranquire

& maybe have the same copyright here:
https://github.com/Galad/tranquire/blob/master/src/Nuget/Tranquire.nuspec#L13

Regards

Thomas

**Comment by Galad** [comment]
Done, thanks.
