### ISSUE TITLE
Letting the actor navigate to url

### ISSUE THREAD

**Issue by Deeviej** [Galad/tranquire#117]
I don't know if I'm in the right place here to ask a question about the screenplay I'm trying to set up myself, but I'll try it anyway. 

I want my actor to navigate to an url as it shows in this tutorial:  
//Execute the action in the Given context
john.Given(Navigate.ToUrl("http://localhost:57897"));

But I get the message: Navigate does not contain a definition for 'ToUrl'. Probably there is something wrong with the code. I hope I formulated my question clear enough, since I just started my job in IT. Here's my code: 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Tranquire.Selenium;
using Tranquire;
using iTraffic360Selenium.PageObjects;
using iTraffic360Selenium.PageObjects.CRUD;
using NUnit.Framework;
using OpenQA.Selenium.Firefox;
using iTraffic360Selenium;
using Tranquire.Selenium.Actions;
using Tranquire.Extensions;
using Tranquire.ActionBuilders;
using Tranquire.Selenium.Extensions;

namespace iTraffic360Specflow
{
    class ScreenPlayPatern

    {

        public void TryToLogin()
        {
            var john = new Actor("John");
            var driver = new FirefoxDriver();
            driver.Manage().Window.Maximize();

            john.CanUse(WebBrowser.With(driver));
            john.Given(Navigate.ToUrl("https://eal-test-itraffic360.eal.nl"));
        }

    }

}

**Comment by thePantz** [comment]
If you're trying to use [Tranquires Navigate Class ](https://github.com/Galad/tranquire/blob/0d68debdc38376600d1325cbee2ca3aef069dce9/src/Tranquire.Selenium/Actions/Navigate.cs) it uses the .To(uri) method.

For example:
`Navigate.To(new Uri("https://eal-test-itraffic360.eal.nl"))`



@Galad Just noticed that this seems to be missing an overload to accept a plain string. Is there a reason only Uri is supported? I've noticed that in your ToDoList example you implemented a completely separate Navigate class [here](https://github.com/Galad/tranquire/blob/0d68debdc38376600d1325cbee2ca3aef069dce9/src/ToDoList.Automation/Actions/Navigate.cs).

**Comment by Galad** [comment]
@thePantz 
No there is no particular reason. Adding the overload is a good idea.
I think that the `Navigate` class was not there at the begining and was added later because it is really trivial, that is why there is a separate class.

I'll update the sample project to use the built-in `Navigate` class, thanks for noticing it.

@Deeviej How did you come up with `Navigate.ToUrl` ?

**Comment by Deeviej** [comment]
@thePantz 
Thank you, I will try that. 

@Galad 
I saw it before in the tutorial/wiki: https://github.com/Galad/tranquire/wiki/Overview. it was mentioned as following: 

//Execute the action in the Given context
john.Given(Navigate.ToUrl("http://localhost:57897"));

I can't seem to find it now anymore though.
